package com.thinh.pomodoro.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006B5D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF6EF9DF)
val md_theme_light_onPrimaryContainer = Color(0xFF00201B)
val md_theme_light_secondary = Color(0xFF00696E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF6FF6FF)
val md_theme_light_onSecondaryContainer = Color(0xFF002022)
val md_theme_light_tertiary = Color(0xFFA14000)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBCC)
val md_theme_light_onTertiaryContainer = Color(0xFF351000)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF3FEFF)
val md_theme_light_onBackground = Color(0xFF002022)
val md_theme_light_surface = Color(0xFFF5F5F5)
val md_theme_light_onSurface = Color(0xFF002022)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E1)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4946)
val md_theme_light_outline = Color(0xFF6F7976)
val md_theme_light_inverseOnSurface = Color(0xFFC3FBFF)
val md_theme_light_inverseSurface = Color(0xFF00373A)
val md_theme_light_inversePrimary = Color(0xFF4CDCC4)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006B5D)
val md_theme_light_outlineVariant = Color(0xFFBEC9C5)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF4CDCC4)
val md_theme_dark_onPrimary = Color(0xFF00382F)
val md_theme_dark_primaryContainer = Color(0xFF005045)
val md_theme_dark_onPrimaryContainer = Color(0xFF6EF9DF)
val md_theme_dark_secondary = Color(0xFF4CD9E2)
val md_theme_dark_onSecondary = Color(0xFF00373A)
val md_theme_dark_secondaryContainer = Color(0xFF004F53)
val md_theme_dark_onSecondaryContainer = Color(0xFF6FF6FF)
val md_theme_dark_tertiary = Color(0xFFFFB694)
val md_theme_dark_onTertiary = Color(0xFF571F00)
val md_theme_dark_tertiaryContainer = Color(0xFF7B2F00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBCC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF002022)
val md_theme_dark_onBackground = Color(0xFF70F5FF)
val md_theme_dark_surface = Color(0xFF002022)
val md_theme_dark_onSurface = Color(0xFF70F5FF)
val md_theme_dark_surfaceVariant = Color(0xFF3F4946)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C5)
val md_theme_dark_outline = Color(0xFF89938F)
val md_theme_dark_inverseOnSurface = Color(0xFF002022)
val md_theme_dark_inverseSurface = Color(0xFF70F5FF)
val md_theme_dark_inversePrimary = Color(0xFF006B5D)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF4CDCC4)
val md_theme_dark_outlineVariant = Color(0xFF3F4946)
val md_theme_dark_scrim = Color(0xFF000000)

// working_light_theme
val working_light_primary = Color(0xFF471515)
val working_light_background = Color(0xFFFFF2F2)
val working_light_secondary = Color(0x26FF4C4C)
val working_light_tertiary = Color(0xB3FF4C4C)

// working_dark_theme
val working_dark_primary = Color(0xFFFFF2F2)
val working_dark_background = Color(0xFF0D0404)
val working_dark_secondary = Color(0x26FF4C4C)
val working_dark_tertiary = Color(0xB3FF4C4C)

// short_break_light_theme
val short_break_light_primary = Color(0xFF14401D)
val short_break_light_background = Color(0xFFF2FFF5)
val short_break_light_secondary = Color(0x264DDA6E)
val short_break_light_tertiary = Color(0x9E4DDA6E)

// short_break_dark_theme
val short_break_dark_primary = Color(0xFFF2FFF5)
val short_break_dark_background = Color(0xFF0D0404)
val short_break_dark_secondary = Color(0x264DDA6E)
val short_break_dark_tertiary = Color(0x9E4DDA6E)

// long_break_light_theme
val long_break_light_primary = Color(0xFF153047)
val long_break_light_background = Color(0xFFF2F9FF)
val long_break_light_secondary = Color(0x264CACFF)
val long_break_light_tertiary = Color(0x9E4CACFF)

// long_break_dark_theme
val long_break_dark_primary = Color(0xFFF5F2FF)
val long_break_dark_background = Color(0xFF0D0404)
val long_break_dark_secondary = Color(0x264CACFF)
val long_break_dark_tertiary = Color(0x9E4CACFF)


